# Generated by Django 5.2.7 on 2025-11-04 17:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscalaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombres_y_apellidos', models.CharField(max_length=255)),
                ('unidad_de_adscripcion_y_o_direccion', models.CharField(max_length=200)),
                ('estado_o_ubicacion', models.CharField(max_length=100)),
                ('codigo_del_cargo', models.CharField(max_length=50, null=True)),
                ('fecha_de_ingreso', models.DateField()),
                ('grado_de_instruccion', models.CharField(max_length=100)),
                ('anos_previos', models.IntegerField(default=0)),
                ('anos_en_fundabit', models.IntegerField(default=0)),
                ('total_anos_de_servicios', models.IntegerField(default=0)),
                ('numero_de_hijos', models.IntegerField(default=0)),
                ('discapacitado', models.BooleanField(default=False)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='nomina.cargo')),
                ('condicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='nomina.condicion')),
                ('escala_salarial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='nomina.escalasalarial')),
            ],
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_de_cuenta', models.BigIntegerField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_bancarios', to='nomina.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmpleado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cedula', models.IntegerField(db_index=True)),
                ('nombres_y_apellidos', models.CharField(max_length=255)),
                ('unidad_de_adscripcion_y_o_direccion', models.CharField(max_length=200)),
                ('estado_o_ubicacion', models.CharField(max_length=100)),
                ('codigo_del_cargo', models.CharField(max_length=50, null=True)),
                ('fecha_de_ingreso', models.DateField()),
                ('grado_de_instruccion', models.CharField(max_length=100)),
                ('anos_previos', models.IntegerField(default=0)),
                ('anos_en_fundabit', models.IntegerField(default=0)),
                ('total_anos_de_servicios', models.IntegerField(default=0)),
                ('numero_de_hijos', models.IntegerField(default=0)),
                ('discapacitado', models.BooleanField(default=False)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.cargo')),
                ('condicion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.condicion')),
                ('escala_salarial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nomina.escalasalarial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical empleado',
                'verbose_name_plural': 'historical empleados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Quincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('fecha', models.DateField()),
                ('dias_laborados', models.IntegerField(default=0)),
                ('horas_extras_quincena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_retroactivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_asignacion_primera_quincena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_asignacion_segunda_quincena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_de_asignacion_quincenal_todos_los_conceptos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_asignacion_mensual_todos_los_conceptos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_a_cancelar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quincenas', to='nomina.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion_por_caja_de_ahorro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retencion_por_sso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retencion_rpe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retencion_por_faov', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retencion_por_fejp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sinaep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ipasme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_por_pago_indebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quincena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='nomina.quincena')),
            ],
        ),
        migrations.CreateModel(
            name='DeduccionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('quincena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deducciones_adicionales', to='nomina.quincena')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionesQuincenales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_de_antiguedad_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_de_profesionalizacion_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_por_hijos_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribucion_para_trabajadoras_y_trabajadores_con_discapacidad_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complemento_del_salario_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('becas_para_hijos_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_asistencial_y_del_hogar_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_trabajadores_adm_y_obr_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encargaduria_quincenal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia_por_comisiones_de_servicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_prima_de_antiguedad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_prima_de_profesionalizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_prima_por_hijos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_contribucion_para_trabajadoras_y_trabajadores_con_discapacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_becas_para_hijos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_prima_asistencial_y_del_hogar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_prima_trabajadores_adm_y_obr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retroactivo_encargaduria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quincena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_quincenales', to='nomina.quincena')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionesMensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_de_antiguedad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prima_de_profesionalizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_por_hijos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribucion_para_trabajadoras_y_trabajadores_con_discapacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complemento_del_salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('becas_para_hijos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_asistencial_y_del_hogar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima_trabajadores_adm_y_obr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encargaduria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quincena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mensuales', to='nomina.quincena')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAdicionalQuincenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('quincena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_quincenales_adicionales', to='nomina.quincena')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAdicionalMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('quincena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mensuales_adicionales', to='nomina.quincena')),
            ],
        ),
    ]
