# Generated by Django 5.2.7 on 2025-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quincena',
            name='bono_alimenticio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
