# Generated by Django 5.2.7 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_quincena_bono_alimenticio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionadicionalmensual',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='asignacionadicionalquincenal',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
