# Generated by Django 5.2.7 on 2025-11-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_asignacionadicionalmensual_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tipo', models.CharField(choices=[('constancia', 'Constancia'), ('recibo', 'Recibo')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pdf', to='nomina.empleado')),
                ('quincena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pdf', to='nomina.quincena')),
            ],
        ),
    ]
